### ISSUE TITLE
DB.Add<T>(T model)

### ISSUE THREAD

**Issue by NikaBuligini** [tungula/StrategyOrbit#2]
მეთოდს სჭირდება property-ების სახელების ბაზაში შემოწმება. ვერ აკეთებს იმ მოდელის insert-ს, რომელსაც ისეთი property-ები აქვთ, რომელთა სახელები ცხრილში არ არის.

ასევე გჭირდება ამ მეთოდმა დააბრუნოს insert-ის ID. რაღაც სიტუაციებში გვჭირდება

**Comment by tungula** [comment]
Fixed
